name: Terraform

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Check-terraform:
    runs-on: ubuntu-latest
    name: Check-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        run: terraform fmt -check
      
      - name: terraform init
        run: terraform init
      
      - name: terraform validate
        run: terraform validate
