name: Check_terraform 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Check_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ../../
      
      - name: terraform init
        run: terraform init
      
      - name: terraform validate
        run: terraform validate
